# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DateTime-Incomplete
version:      0.0301
version_from: lib/DateTime/Incomplete.pm
installdirs:  site
requires:
    DateTime:                      0
    DateTime::Event::Recurrence:   0
    DateTime::Set:                 0.1401
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
